"""Business layer: project registry and operations reporting."""
from __future__ import annotations

from datetime import timedelta

from friday.clock import iso, parse_iso

# The user's stated business structure. These are organisational labels only — no business data is invented.
SEED_PROJECTS = [
    ("CyZy", None, "Malaysia-based business ecosystem (parent project)"),
    ("CyZy GC", "CyZy", "CyZy division"),
    ("CyZy Global Ticketing", "CyZy", "CyZy division"),
    ("CyZy FX", "CyZy", "Financial-services-related operations (educational/research focus; regulated activity needs human review)"),
    ("Finance Education", "CyZy", "Finance education and content"),
]


def seed_projects(db, clock) -> None:
    for name, parent, desc in SEED_PROJECTS:
        db.execute("INSERT OR IGNORE INTO projects(name,parent,description,created) VALUES (?,?,?,?)",
                   (name, parent, desc, iso(clock.now())))


def list_projects(db) -> list[dict]:
    return [dict(r) for r in db.query("SELECT * FROM projects ORDER BY id")]


def project_names(db) -> list[str]:
    return [r["name"] for r in db.query("SELECT name FROM projects")]


def operations_report(svc, project: str | None) -> str:
    now = svc.clock.now()
    z = svc.config.zone
    t = svc.tasks
    loc = now.astimezone(z)
    title = f"{project or 'All projects'} — Operations Report"
    open_t = t.list(open_only=True, project=project)
    overdue = [x for x in open_t if x["deadline"] and parse_iso(x["deadline"]) < now]
    week_ago = now - timedelta(days=7)
    done_week = [x for x in t.completed_between(week_ago, now + timedelta(seconds=1)) if not project or x["project"] == project]
    blockers = t.blockers(project)

    def line(x):
        due = parse_iso(x["deadline"]).astimezone(z).strftime("%d %b %H:%M") if x["deadline"] else "no deadline"
        return f"- #{x['id']} **{x['title']}** — {x['priority_name']}, {due}" + (f" ({x['project']})" if x["project"] and not project else "")

    L = [f"# {title}", "", f"_Generated by FRIDAY on {loc.strftime('%A %d %B %Y %H:%M')} ({svc.config.tz})._", "",
         "## Summary", "",
         f"- Open tasks: **{len(open_t)}** (overdue: **{len(overdue)}**, blocked: **{len(blockers)}**)",
         f"- Completed in the last 7 days: **{len(done_week)}**", "", "## Next priorities", ""]
    L += [line(x) for x in t.next_actions(7, project)] or ["- none recorded"]
    L += ["", "## Overdue", ""] + ([line(x) for x in overdue] or ["- none"])
    L += ["", "## Blocked", ""]
    L += [f"- #{b['id']} **{b['title']}** — waiting on " + (", ".join(f"#{w['id']} {w['title']}" for w in b["waiting_on"]) or "(marked blocked)")
          for b in blockers] or ["- none"]
    L += ["", "## Completed this week", ""] + ([line(x) for x in done_week] or ["- none"])
    notes = svc.memory.list("business", limit=10)
    if project:
        notes = [n for n in notes if n["project"] == project]
    L += ["", "## Business notes (from memory)", ""] + ([f"- {n['content'][:200]}" for n in notes[:8]] or ["- none stored"])
    recent = [r for r in svc.audit.recent(100) if parse_iso(r["ts"]) > week_ago][:8]
    L += ["", "## Recent FRIDAY activity", ""] + ([f"- {r['ts'][:16]} `{r['tool']}` {r['status']}: {r['summary'][:100]}" for r in recent] or ["- none"])
    L += ["", "## Not covered", "",
          "No data source is connected yet for: leads, sales, invoices/payments, customer conversations, marketing or ticketing activity. "
          "This report only reflects tasks, memory and FRIDAY's own activity log.", ""]
    return "\n".join(L)
